config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'
  get 'tags/show'
  # require 'sidekiq/web'
  # require 'admin_constraint'

  # Sidekiq admin interface
  # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  # Root route
  root 'index#index'

  # Error routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Authentication routes
  post 'signup', to: 'users#create', as: 'signup'
  post 'login', to: 'sessions#create', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'get-started', to: 'index#buy_sell', as: 'get_started'

  # Mobile routes
  get 'mobile', to: 'sessions#mobile', as: 'mobile'
  get 'mobile/signup', to: 'sessions#mobile_signup'
  get 'admin/login', to: 'sessions#mobile_login', as: 'mobile_login'
  get 'welcome-back', to: 'sessions#welcome_back_user', as: 'welcome_back_user'

  # Password routes
  get 'forgot-my-password', to: 'users#forgot_my_password'
  post 'send-token-email', to: 'users#send_token_email'
  get 'new-token-email', to: 'users#new_token_confirmation'
  get 'validate-token/:token', to: 'users#validate_token'
  post 'update-password', to: 'users#update_password'
  post 'change-password', to: 'users#change_password'
  get 'complete_signup/:token', to: 'users#complete_signup'

  # Index page routes
  # get 'background', to: 'index#background'
  # get 'about', to: 'index#about'
  # get 'faq', to: 'index#faq'
  get 'contact', to: 'index#contact'
  post 'contact', to: 'admin#contact_team', as: 'contact_us'
  # get 'step-by-step', to: 'index#step_by_step', as: 'guide'
  get 'privacy-policy', to: 'index#policy', as: 'policy'
  get 'ipad', to: 'index#device_warning'

  # Terms and conditions
  get 'terms-and-conditions', to: 'index#terms_and_conditions'
  get 'accept/:user_id', to: 'users#accept', as: 'accept'

  # Resourceful routes
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :apartments, path: 'listings' do
    resources :comments, only: [:create]
    resources :photo_descriptions, only: [] do
      collection do
        patch :update_all
      end
    end
    resources :market_scores, only: [:create]
    resources :floorplans, only: %i[create destroy update]
  end

  resources :favourites
  resources :photos
  resources :replies
  # config/routes.rb
  resources :tags, path: 'categories', param: :slug do
    resources :child_tags, only: [:show], param: :slug, controller: 'tags'
  end


  # Apartment search routes
  get 'sub-search', to: 'apartments#search_page_two', constraints: lambda { |request| request.query_parameters[:commit] == 'SEARCH' }, as: 'search_page_two'
  get 'search-page', to: 'apartments#search_page_one', as: 'search_page_one'
  get 'search_location/:data', to: 'apartments#search_location'
  get 'submit', to: 'apartments#submit', as: 'submit'
  get 'location-data', to: 'postcodes#typeahead_data'
  get 'property-search', to: 'apartments#new_index'
  get 'location', to: 'apartments#new'
  get 'myproperties', to: 'apartments#owner'
  get 'saved_search/:id', to: 'apartments#index', as: 'saved_search'
  get 'search', to: 'apartments#search'
  get 'searches', to: 'apartments#return_to_search_results', as: 'return_to_search_results'
  get 'photos/featured', to: 'photos#featured'

  # Comments, replies & likes
  post 'comments/:id/:user_id', to: 'apartments#comment'
  delete 'comments/:id', to: 'comments#delete', as: 'delete_comment'
  post 'like/:like_id', to: 'comments#like', as: 'like_comment'

  # Admin section
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/directory', to: 'admin#directory', as: 'admin_directory'
  post 'approve/:id', to: 'admin#approve', as: 'approval'
  post 'revoke/:id', to: 'admin#revoke', as: 'revoke'
  get 'delete/:id', to: 'admin#delete', as: :admin_deletion
  get 'admin/archive/:id', to: 'admin#archive', as: 'admin_archive'
  get 'admin/unarchive/:id', to: 'admin#unarchive', as: 'admin_unarchive'
  get 'admin/archival', to: 'admin#archival', as: 'archival'
  get 'admin/owner/:user_id', to: 'admin#owner', as: 'admin_owner'
  delete 'delete_saved_search/:id', to: 'searches#delete', as: 'delete_saved_search'
  namespace :admin do
    resources :tags do
      collection do
        post 'assign_tags'
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
  # Catch-all route for 404 errors
  # match '*path', to: 'errors#not_found', via: :all
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                            :bigint           not null, primary key
#  accepted_terms_and_conditions :boolean          default(FALSE)
#  email                         :string
#  firstname                     :string
#  is_admin                      :boolean          default(FALSE)
#  last_search_query_match       :datetime
#  password_digest               :string
#  password_token_valid_until    :datetime
#  phone                         :string
#  reset_password_token          :string
#  surname                       :string
#  username                      :string
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#
# Indexes
#
#  index_users_on_email     (email) UNIQUE
#  index_users_on_username  (username) UNIQUE
#

class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar, dependent: :destroy
  has_many :apartments, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :searches, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_milestones, dependent: :destroy

  has_and_belongs_to_many :favourites, class_name: "Apartment"
  accepts_nested_attributes_for :user_milestones

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, on: [:create]

  after_create_commit :send_email_address_confirmation

  def is_admin?
    is_admin == true
  end

  def set_password_token(valid_for:)
    return false unless valid_for.class == ActiveSupport::Duration
    self.update(reset_password_token: SecureRandom.alphanumeric(20))
    self.update(password_token_valid_until: Time.now + valid_for)
  end

  def total_properties
    apartments.load.size
  end

  def accepted_terms?
    accepted_terms_and_conditions == true
  end

  def unlike(comment)
    comment.likes.find_by_user_id(self.id)&.delete
  end

  def like(comment)
    comment.likes.create!(user_id: self.id)
  end

  def milestones
    user_milestones
  end

  def already_liked_comment?(comment)
    comment.likes.find_by_user_id(self.id).present?
  end

  def self.summary
    ap pluck :email,:id,:username
  end

  private

  def send_email_address_confirmation
    User::RequestEmailAddressConfirmationJob.perform(user_id: self.id)
  end

end

app/views/admin/_tag_select.html.erb
<%= form_with(model: apartment, local: true) do |form| %>
  <div class="field">
    <%= form.collection_select :tag_ids, @child_tags, :id, :name, { prompt: "Choose a Child Tag" }, { multiple: true } %>
  </div>
  <div class="actions">
    <%= form.submit "Assign to Category" %>
  </div>
<% end %>

app/views/admin/archival.html.erb
<br>
<div class="col-md-4"></div>
<p class="text-center mt-md-5 ml-md-5 display-4 property-title">ARCHIVAL SECTION</p>
<div class="col-md-3"></div>
<div class="col-md-3"></div>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
  <table class="table" id="adminTable">
      <thead>
        <% if @apartments.empty? %>
        <p class="text-center mt-md-5 ml-md-5 display-5 property-title">None Archived</p>
        <% else %>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Address</th>
          <th scope="col">User</th>
          <th scope="col">Status</th>
         <th scope="col">Actions
          <%= link_to "View Archive", archival_path %>
         </th>
        </tr>
      </thead>
      <tbody>
        <% end %>
        <% @apartments.each_with_index do |apartment,i| %>
        <tr>
          <th scope="row"><span><%= i+1 %></span></th>
          <td><%= link_to "#{apartment.house_number} #{apartment.street_address}, #{apartment.suburb} #{apartment.postcode}", apartment_path(apartment), class: "page-link" %></td>
          <td><%= link_to "#{apartment.user.username}  / #{apartment.user.email} (#{apartment.user.total_properties}) ", admin_owner_path(apartment.user), class: "page-link" %></td>
          <td>
            <span class='btn btn-secondary'>Archived</span>
          </td>
          <td>
            <%= link_to("UnArchive", admin_unarchive_path(apartment), class: "btn btn-primary", method: "post") %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/admin/contact_team.html.erb
<div class="row">
  <div class="column col-md-2" id="contact-column"></div>
  <div class="col-md-8 mt-md-5">
    <h3 class="text-center mt-md-5 mb-md-3">Thank you</h3>
    <p class="text-center">Your message has been sent successfully.</p>
    <p class="text-center"> We'll be in touch as soon as possible.</p>
    <div class="row mt-md-3 mb-md-5">
      <div class="mx-auto mb-md-5">
        <%= link_to "Home", root_path, class:"btn btn-outline-primary"  %>
      </div>
    </div>
  </div>
  <div class="column col-md-2"></div>
</div>

app/views/admin/directory.html.erb
<div class="container my-4">
  <h2>Directory</h2>
  <div class="row">
    <%# Section for 'tags' routes %>
    <div class="col-md-4">
      <h4>Tags</h4>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to 'Tags Index', admin_tags_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'New Tag', new_admin_tag_path, class: 'btn btn-primary btn-block' %>
        </li>
      </ul>
    </div>
    <%# Section for 'sessions' and 'users' routes %>
    <div class="col-md-4">
      <h4>Sessions & Users</h4>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to 'Sign Up', signup_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Login', login_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Logout', logout_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Forgot My Password', forgot_my_password_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Update Password', update_password_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Change Password', change_password_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Users (Index)', users_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'New User', new_user_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Edit User', edit_user_path('id-placeholder'), class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Show User', user_path('id-placeholder'), class: 'btn btn-primary btn-block' %>
        </li>
      </ul>
    </div>
    <%# Section for 'apartments' routes %>
    <div class="col-md-4">
      <h4>Apartments</h4>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to 'Apartments (Index)', apartments_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'New Apartment', new_apartment_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Edit Apartment', edit_apartment_path('id-placeholder'), class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Show Apartment', apartment_path('id-placeholder'), class: 'btn btn-primary btn-block' %>
        </li>
      </ul>
    </div>
    <%# Section for 'admin' routes %>
    <div class="col-md-4">
      <h4>Admin</h4>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to 'Admin Dashboard', admin_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Tags (Admin)', admin_tags_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'New Tag (Admin)', new_admin_tag_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Edit Tag (Admin)', edit_admin_tag_path('id-placeholder'), class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Show Tag (Admin)', admin_tag_path('id-placeholder'), class: 'btn btn-primary btn-block' %>
        </li>
      </ul>
    </div>
    <%# Section for 'errors' %>
    <div class="col-md-4">
      <h4>Error Pages</h4>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to '404 Error', '/404', class: 'btn btn-danger btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to '500 Error', '/500', class: 'btn btn-danger btn-block' %>
        </li>
      </ul>
    </div>
    <%# Section for other routes %>
    <div class="col-md-4">
      <h4>Miscellaneous</h4>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to 'Home', root_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Contact', contact_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Terms and Conditions', terms_and_conditions_path, class: 'btn btn-primary btn-block' %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Privacy Policy', policy_path, class: 'btn btn-primary btn-block' %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<div class="container g-0 col-lg-10 bg-white rounded-3 m-auto">
  <h2 class="text-center mt-md-5 ml-md-5 property-title">ADMIN SECTION</h2>
  <div class="col-md-3"></div>
  <div class="col-md-3"></div>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 table-responsive">
      <table class="table table-sm" id="adminTable">
        <thead>
          <tr>
            <th scope="col" style="font-size:12px;color:#ccc;"></th>
            <th scope="col" style="font-size:12px;color:#ccc;">Address</th>
            <th scope="col" style="font-size:12px;color:#ccc;">User</th>
            <th scope="col" style="font-size:12px;color:#ccc;">Status</th>
            <th scope="col" style="font-size:12px;color:#ccc;">Actions
              <%= link_to "View Archive", archival_path %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @apartments.each_with_index do |apartment,i| %>
            <tr>
              <th scope="row"><span><%= i+1 %></span></th>
              <td><%= link_to "#{apartment.house_number} #{apartment.street_address}, #{apartment.suburb} #{apartment.postcode}", apartment_path(apartment), class: "page-link" %></td>
              <td><%= link_to "#{apartment.user.username}  / #{apartment.user.email} (#{apartment.user.total_properties}) ", admin_owner_path(apartment.user), class: "page-link" %></td>
              <td>
                <%= apartment.approved? ? "<span class='btn btn-success'>Live</span>".html_safe : "<span class='btn btn-danger'>Offline</span>".html_safe %>
              </td>
              <td>
                <% if apartment.approved? %>
                  <a href="<%= revoke_path(apartment) %>" class="btn btn-primary" data-method="post">Revoke</a>
                <% else %>
                  <a href="<%= approval_path(apartment) %>" class="btn btn-primary" data-method="post">Approve</a>
                <% end %>
                <%= link_to("Edit", edit_apartment_path(apartment), class: "btn btn-primary")%>
                <%= link_to("Archive", admin_archive_path(apartment), class: "btn btn-primary", method: "post")%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>