config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'
  get 'tags/show'
  # require 'sidekiq/web'
  # require 'admin_constraint'

  # Sidekiq admin interface
  # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  # Root route
  root 'index#index'

  # Error routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Authentication routes
  post 'signup', to: 'users#create', as: 'signup'
  post 'login', to: 'sessions#create', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'get-started', to: 'index#buy_sell', as: 'get_started'

  # Mobile routes
  get 'mobile', to: 'sessions#mobile', as: 'mobile'
  get 'mobile/signup', to: 'sessions#mobile_signup'
  get 'admin/login', to: 'sessions#mobile_login', as: 'mobile_login'
  get 'welcome-back', to: 'sessions#welcome_back_user', as: 'welcome_back_user'

  # Password routes
  get 'forgot-my-password', to: 'users#forgot_my_password'
  post 'send-token-email', to: 'users#send_token_email'
  get 'new-token-email', to: 'users#new_token_confirmation'
  get 'validate-token/:token', to: 'users#validate_token'
  post 'update-password', to: 'users#update_password'
  post 'change-password', to: 'users#change_password'
  get 'complete_signup/:token', to: 'users#complete_signup'

  # Index page routes
  # get 'background', to: 'index#background'
  # get 'about', to: 'index#about'
  # get 'faq', to: 'index#faq'
  get 'contact', to: 'index#contact'
  post 'contact', to: 'admin#contact_team', as: 'contact_us'
  # get 'step-by-step', to: 'index#step_by_step', as: 'guide'
  get 'privacy-policy', to: 'index#policy', as: 'policy'
  get 'ipad', to: 'index#device_warning'

  # Terms and conditions
  get 'terms-and-conditions', to: 'index#terms_and_conditions'
  get 'accept/:user_id', to: 'users#accept', as: 'accept'

  # Resourceful routes
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :apartments, path: 'listings' do
    resources :comments, only: [:create]
    resources :photo_descriptions, only: [] do
      collection do
        patch :update_all
      end
    end
    resources :market_scores, only: [:create]
    resources :floorplans, only: %i[create destroy update]
  end

  resources :favourites
  resources :photos
  resources :replies
  # config/routes.rb
  resources :tags, path: 'categories', param: :slug do
    resources :child_tags, only: [:show], param: :slug, controller: 'tags'
  end


  # Apartment search routes
  get 'sub-search', to: 'apartments#search_page_two', constraints: lambda { |request| request.query_parameters[:commit] == 'SEARCH' }, as: 'search_page_two'
  get 'search-page', to: 'apartments#search_page_one', as: 'search_page_one'
  get 'search_location/:data', to: 'apartments#search_location'
  get 'submit', to: 'apartments#submit', as: 'submit'
  get 'location-data', to: 'postcodes#typeahead_data'
  get 'property-search', to: 'apartments#new_index'
  get 'location', to: 'apartments#new'
  get 'myproperties', to: 'apartments#owner'
  get 'saved_search/:id', to: 'apartments#index', as: 'saved_search'
  get 'search', to: 'apartments#search'
  get 'searches', to: 'apartments#return_to_search_results', as: 'return_to_search_results'
  get 'photos/featured', to: 'photos#featured'

  # Comments, replies & likes
  post 'comments/:id/:user_id', to: 'apartments#comment'
  delete 'comments/:id', to: 'comments#delete', as: 'delete_comment'
  post 'like/:like_id', to: 'comments#like', as: 'like_comment'

  # Admin section
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/directory', to: 'admin#directory', as: 'admin_directory'
  post 'approve/:id', to: 'admin#approve', as: 'approval'
  post 'revoke/:id', to: 'admin#revoke', as: 'revoke'
  get 'delete/:id', to: 'admin#delete', as: :admin_deletion
  get 'admin/archive/:id', to: 'admin#archive', as: 'admin_archive'
  get 'admin/unarchive/:id', to: 'admin#unarchive', as: 'admin_unarchive'
  get 'admin/archival', to: 'admin#archival', as: 'archival'
  get 'admin/owner/:user_id', to: 'admin#owner', as: 'admin_owner'
  delete 'delete_saved_search/:id', to: 'searches#delete', as: 'delete_saved_search'
  namespace :admin do
    resources :tags do
      collection do
        post 'assign_tags'
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
  # Catch-all route for 404 errors
  # match '*path', to: 'errors#not_found', via: :all
end

app/views/index/_buying_guide.html.erb
<ul>
   <% if device_is_mobile? %>
<h5 class="mt-3">BUYING A PROPERTY</h5>
  <% else %>
<h3>BUYING A PROPERTY</h3>
  <% end %>
<p class="mt-md-4">
  <b>Step 1</b>
  <br>
  <p>Ensure your financing is in order with either available cash or a mortgage pre-approval.</p>
</p>  
<p class="mt-md-4">
  <b>Step 2
</b>
  <br>
  <p>Determine your requirements by making a list of must-haves and would-likes.</p>
</p>  
<p class="mt-md-4">
  <b>Step 3</b>
  <br>
  <p>Enter your requirements into the search engine to see if any properties match your requirements.</p>
</p>
<p class="mt-md-4">
  <b>Step 4</b>
  <br>
  <p>Save your search and wait for notifications as properties come up which match your requirements.</p>
</p>  
<p class="mt-md-4">
  <b>Step 5</b>
  <br>
  <p>If you see a property on the site that you are interested in, contact t('') to arrange an inspection that suits you and the Buyer. Be prepared to answer some questions to qualify you as a genuine Buyer.</p>
</p>  
<p class="mt-md-4">
  <b>Step 6</b>
  <br>
  <p>If you view the property and are interested, make an offer via <%= t("business.name") %>'s trusted advisors and enter into negotiations.</p>
</p>  
<p class="mt-md-4">
  <b>Step 7</b>
  <br>
  <p>If you reach an agreed price to buy, you can request a pest and building or strata report to be commissioned at your own cost for peace of mind.</p>
</p>  
<p class="mt-md-4">
  <b>Step 8</b>
  <br>
  <p>Request for a contract of the property to be reviewed by your solicitor or conveyancer and come to agreement on terms with the Seller.</p>
</p>  
<p class="mt-md-4">
  <b>Step 9</b>
  <br>
  <p>Arrange for exchange of contracts with the Seller by providing a 10% deposit and a s66W waiver of cooling off period.</p>
</p>  
<p class="mt-md-4">
  <b>Step 10</b>
  <br>
  <p>Arrange for a pre-settlement inspection of the property just prior to scheduled settlement.</p>
</p>  
<p class="mt-md-4">
  <b>Step 11</b>
  <br>
  <p>Arrange for settlement of remaining funds and pick up the keys to your new property.</p>
</p>
</ul>
<div class="desktop-break"></div>
<div class="mobile-break"></div>

app/views/index/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-white navbar navbar-expand-md navbar-dark bg-dark">
        <div class="text-white navbar navbar-expand-md navbar-dark bg-dark">
          <%= image_tag(get_aws_url("logo.png")) %>
        </div>
      </div>
      <div class="modal-body">
        <div class="container" id=myGroup>
          <div class="collapse" id="collapseExample" data-parent="#myGroup">
            <div class="card card-body">
              <p>Choose a Username</p>
              <%= form_with url: signup_path do |f| %>

              <div class="field">
                <%= f.hidden_field(:url, value: request.original_fullpath) %>
                <%= f.text_field :username, autofocus: true, placeholder:"Username*" %>
              </div>
              <div class="field">
                <br>
              <p>Your details</p>
                <%= f.text_field :firstname, autofocus: true, placeholder:"First Name*" %>
                <%= f.text_field :surname, placeholder: "Surname*" %>
                <br>
                <br>
                <%= f.telephone_field :phone, placeholder: "Mobile" %><%= f.email_field :email, autocomplete: "email", placeholder: "Email*" %>
              </div>

              <div class="field">
                <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %><br />
                <%= f.password_field :password, autocomplete: "new-password", placeholder: "Password*" %>
                <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "Confirm Password*" %>
              </div>
              <br>
              <div class="actions">
                <%= f.submit "Sign up", class:"btn btn-info"  %>
                <button type="button" class="btn btn-outline-primary new-existing-user" data-target="#collapseExample2" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Existing User?</button>
              </div>
              <% end %>
            </div>
          </div>
          <div class="collapse show" id="collapseExample2" data-parent="#myGroup">
            <div class="card card-body">
              <p>Already Registered? Log In</p>
              <%= form_with url: login_path do |f| %>
              <div class="field">
                <%= f.hidden_field(:url, value: request.original_fullpath) %>
                <%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true, autocomplete: "Email" %>
              </div>
              <div class="field">
                <%= f.label :password %><br />
                <%= f.password_field :password, autocomplete: "current-password" %>
              </div>
              <br>
              <div class="actions">
                <%= f.submit "Log in", class:"btn btn-info" %>
                <button type="button" class="btn btn-outline-primary new-existing-user" data-target="#collapseExample" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">New User?</button>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer text-white navbar navbar-expand-lg navbar-dark bg-dark">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/index/_selling_guide.html.erb
<ul>
 <% if device_is_mobile? %>
 <h5 class="mt-3">SELLING YOUR PROPERTY</h5>
 <% else %>
 <h3>SELLING YOUR PROPERTY</h3>
 <% end %>
 <p class="mt-md-4"><b>Step 1 </b><br></p><p class="mt-md-3">Engage a solicitor or conveyancer to prepare a contract of sale for your home.</p>
 <p class="mt-md-4"><b>Step 2 </b><br></p><p class="mt-md-3"> Declutter, fix, beautify, style and thoroughly clean your home and garden so that it presents well to prospective buyers.</p>
 <p class="mt-md-4"><b>Step 3 </b><br></p><p class="mt-md-3"> Do some local research and decide on the price you wish to sell for.</p>
 <p class="mt-md-4"><b>Step 4 </b><br></p><p class="mt-md-3"> Prepare or order a floorplan for your property.</p>
 <p class="mt-md-4"><b>Step 5 </b><br></p><p class="mt-md-3"> Take yourself or arrange a photographer to take 5-10 photos of the house and any outdoor spaces.</p>
 <p class="mt-md-4"><b>Step 6 </b><br></p><p class="mt-md-3"> Write a description of your property. Get someone impartial to look at it from a prospective buyers viewpoint.</p>
 <p class="mt-md-4"><b>Step 7 </b><br></p><p class="mt-md-3"> List your property on <b><%= t("business.name") %> </b> by adding the photos, floorplan, description and price.</p>
 <p class="mt-md-4"><b>Step 8 </b><br></p><p class="mt-md-3"> Get pricing and general feedback from prospective buyers and adjust your asking price as necessary to make it attractive to sell.</p>
 <p class="mt-md-4"><b>Step 9 </b><br></p><p class="mt-md-3"> Wait for <b><%= t("business.name") %> </b> to make contact about interest in viewing your property. If this isn’t happening in your ideal timeframe, review your pricing strategy and adjust as needed.</p>
 <p class="mt-md-4"><b>Step 10</b><br></p><p class="mt-md-3">  Make your home presentable and available for private inspections from buyers.</p>
 <p class="mt-md-4"><b>Step 11</b><br></p><p class="mt-md-3">  Wait for an offer to be made for your property. Enter negotiations until both parties agree on a suitable price and terms.</p>
 <p class="mt-md-4"><b>Step 12</b><br></p><p class="mt-md-3">  Accept and exchange contracts with the buyer and pay your $5,000 success fee invoice to Homblok.</p>
 <p class="mt-md-4"><b>Step 13</b><br></p><p class="mt-md-3">  Instruct a solicitor or conveyancer to complete the sale.</p>
 <p class="mt-md-4"><b>Step 14</b><br></p><p class="mt-md-3">  Allow the buyer to do a pre-settlement inspection if they request it.</p>
 <p class="mt-md-4"><b>Step 15</b><br></p><p class="mt-md-3">  Finalise the settlement and hand over the keys.</p>
 <p class="mt-md-4"><b></b></p>
</ul>
<div class="mobile-break"></div>
<div class="desktop-break"></div>

app/views/index/about.html.haml
.row
  .column.col-md-2
  .col-md-8
    %h2.text-center.ml-md-4.mt-md-5
      = image_tag "dark_icons/icons8-about-50.png", class: "title-icons ml-md-2 mr-md-1 mb-md-1"
      ABOUT <%= t("business.name") %>
  #aboutus.column.col-md-2
.row
  .column.col-md-2
  .col-md-8
    %ul
      %h3.mt-md-4 ABOUT US
      %h4 The Team
      %li
        %p
          <%= t("business.name") %> s Principal and Founder is
          %a#link5{href: "mailto:#{t("business.email")}"} <%= t("business.contact") %>
          , a qualified Real Estate Agent with her Real Estate Licence and experience in both Buying and Selling property.
      %li
        %p Highly professional, she has a prior extensive background and experience in banking and finance as well as executive search, giving her the attention to detail and communication skills needed across a depth of industries.
      %li
        %p <%= t("business.name") %> consists of a team of qualified professionals who are trained in real estate, understand the market and want to give people more choices and control over their property transactions.
    %ul
      %h4 The Proposition
      %li
        %p An option to showcase your property initially with no commitment or fees.
      %li
        %p A choice to find more stock as a prospective buyer.
      %li
        %p If you become serious to buy or sell, you get the assistance of a qualified negotiator who ensures both sides are treated fairly, and an optimal outcome is achieved at a minimum price.
    %ul
      %h4 The Background
      %li
        %p#theconcept In her roles as Sales Agent and Buyers Agent, Leena has established many relationships with Real Estate Agents which has given her extensive insight into the needs of the market and how to fill the gap in it.
      %li
        %p <%= t("business.name") %> sets out to help people achieve a seamless transaction in one of the biggest decisions they make in their life.
  .column.col-md-2
.row
  .column.col-md-2
  .col-md-8
    %ul.mt-md-3
      %h3 THE CONCEPT
      %h4 Built for Buyers, Seamless for Sellers
      %li
        %p The online Real Estate space in Australia is dominated by realestate.com and domain.com, both charging thousands of dollars for people to showcase their home.
      %li
        %p When someone starts thinking about selling, they need an online platform where they can showcase their property with no commitment or upfront marketing fees.
      %li
        %p When a future Buyer cannot find stock, they need a platform to post their requirements.
      %li
        %p The current market gives people little choice but to sign up exclusively with a Real Estate Agent, pay upfront marketing fees for online advertising, print marketing, signboards, brochures and other marketing tools deemed necessary by agents.
      %li
        %p The process of selling your house as a vendor with an agent is highly stressful and invasive.
      %li
        %p Many Open House visitors are simply window shopping and viewing for pleasure, as opposed to actual qualified Buyers.
      %li
        %p Agents fees charged are not always commensurate with the price achieved for the Seller or the work and effort they put into selling.
      %li
        %p Homblok has come about due to a demand in the market for Sellers to showcase and sell their properties without any upfront marketing fees required.
      %li
        %p There is also a need for Sellers to be able to avoid the high commissions charged by Real Estate Agents if they do achieve a sale. Charging commission as a percentage of the sale price is a dated concept which inflates the commission unnecessarily.
    %ul
      %br
        %h4 The Solution: An Online Platform to Showcase Property
        %li
          %p Homblok is an online platform to encourage anyone to post their property for feedback from the public.
        %li
          %p It&#x2019;s about showcasing your property to others for some initial comments and pricing feedback.
        %li
          %p Conversely, Buyers may not be able to find what they&#x2019;re looking for and wish to post their requirements, allowing a possible Seller to come forward and creating stock for the market.
        %li
          %p If you are not in a hurry to sell your property and you wish to test the market, are not on a strict deadline and have plans to sell in the future, then Homblok is a good option to start with.
        %li
          %p If the Buyer and Seller come together to find a match, then a property sale can take place with negotiation and settlement overseen by a qualified Real Estate Agent to ensure a fair outcome.
        %li
          %p Sellers will be relieved with the absence of publicity, stress of Open Houses and general tension created by a home sale campaign.
        %li
          %p#themechanics A Seller can achieve a home sale completely privately and anonymously without any neighbours, friends and family knowing about it.
  .column.col-md-2
.row
  .column.col-md-2
  .col-md-8
    %ul.mt-md-3
      %h3 THE MECHANICS
      %h4 How it works for future Sellers
      %li
        %p You may be thinking about selling in the future and want some feedback on your home or the price you wish to achieve.
      %li
        %p You may have undertaken a recent renovation or styled your property and want some feedback on it.
      %li
        %p Future Sellers can post a price they wish to achieve, and future Buyers can comment and post the price they believe it&#x2019;s worth.
      %li
        %p If a Seller and Buyer wish to communicate further to discuss a future prospective sales plan, they make contact with Homblok, and a qualified Real Estate Agent becomes involved to negotiate the sale through to exchange and settlement.
      %li
        %p Sellers are encouraged to register under a pseudonym as their Username to protect their anonymity and privacy.
      %br
        %h4 How it works for future Buyers
        %li
          %p If a Buyer cannot find results in their Search on Homblok, they are encouraged to contact Homblok with their requirements and Homblok will use this data to encourage Sellers to post their property if they fit the criteria.
        %li
          %p Similarly, a qualified Real Estate Agent becomes involved as soon as there is a possible negotiation involved.
        %li
          %p The aim is to make it a level playing field for Buyers and Sellers and achieve a fair outcome for both.
        %li
          %p Bringing out Sellers to respond to a Buyer means an increase in stock for Buyers to choose from.
        %br
          %h4 &#x201C;Free&#x201D; to post and search
          %li
            %p There are no hidden fees or charges to post your property, give feedback on other properties or post your requirements.
          %li
            %p If a negotiation comes into play, both Seller and Buyer must agree to the Terms and Conditions of the site. The Seller agrees to pay a fee for service which is payable upon exchange of property contracts of the property, once there has been a successful sale.
          %li
            %p
              Buyers and Sellers can enjoy posting and commenting without fees and charges involved.
          %li
            %p
              The only fees payable are a fixed fee for actual service and success by the Seller in selling their property, which is a fraction of a normal commission charged by a Real Estate Agent.
          %li
            %p The parties still have access to a qualified Real Estate Agent, and peace of mind that a professional is dealing with the process.
          %li
            %p Buyers know it takes time to find the right property and this gives them a platform to seek out stock, especially in the current low-stock environment in the market.
          %li
            %p It&#x2019;s a win-win for both parties if a sale takes place.
          %li
            %p The Seller saves thousands of dollars in marketing costs and commissions.
  .column.col-md-2
.row
  .column.col-md-2

app/views/index/buy_sell.html.erb
<div class="container-fluid g-0">
    <div class="row top-row"></div>
    <div class="row my-5">
        <div class="col-md-2"></div>
        <div class="column col-md-3">
            <div class="buy-sell-box">
                <%= link_to search_path, class: 'nav-item nav-link active' do %>
                <div class="icon-box">
                    <%= image_tag "buy_sell" %>
                </div>
                <% end %>
            </div>
            <h3 class="text-center my-5">I'm buying a property</h3>
        </div>
        <div class="column col-md-2"></div>
        <div class="column col-md-3">
            <%= link_to new_apartment_path, class: 'nav-item nav-link active' do %>
            <div class="buy-sell-box">
                <div class="icon-box">
                    <%= image_tag "buy_sell" %>
                </div>
            </div>
            <% end %>
            <h3 class="text-center my-5">I'm selling a property</h3>
        </div>
    </div>
</div>

app/views/index/contact.html.erb
<div class="row">
  <div class="col-md-4 m-auto">
    <h2 class="text-center my-md-5">Make an Enquiry</h2>
    <%= form_with url: contact_us_path, local:true, class:"form-group" do |f| %>
      <%= image_tag get_aws_url("white_icons/icons8-name-50.png"), class: "feature-icons-edit-new ml-md-2" %>
      <%= f.label :name %>
      <%= f.text_field :firstname, autofocus: true,required:true, placeholder:"Your name", class: "form-control mb-md-3", value: current_user.present? && @apartment.present? ? "#{current_user.firstname} #{current_user.surname}"  : nil %>
      <%= image_tag get_aws_url("white_icons/icons8-mobile-50.png"), class: "feature-icons-edit-new ml-md-2" %>
      <%= f.label :phone %>
      <%= f.text_field :phone, required:true, placeholder: "Your phone number", class: "form-control mb-md-3", value: current_user.present? && @apartment.present? ? "#{current_user.phone}" : nil %>
      <%= image_tag get_aws_url("white_icons/icons8-email-50.png"), class: "feature-icons-edit-new ml-md-2" %>
      <%= f.label :email %>
      <%= f.text_field :email, required:true, placeholder: "Your email address", class: "form-control mb-md-3", value: current_user.present? && @apartment.present? ?  "#{current_user.email}" : nil %>
      <%= image_tag get_aws_url("white_icons/icons8-new-topic-50.png"), class: "feature-icons-edit-new ml-md-2" %>
      <%= f.label :subject %>
      <%= f.text_field :subject, required:true, placeholder: "Your message subject", class: "form-control mb-md-3", value: @apartment.present? ?  "Your property in #{@apartment.suburb} \n": nil  %>
      <%= image_tag get_aws_url("white_icons/icons8-messaging-50.png"), class: "feature-icons-edit-new ml-md-2" %>
      <%= f.label :message %>
      <%= f.text_area :message_body, required:true, placeholder: "Your message", class: "form-control mb-md-3" %>
      <%= f.submit "Send", id: "contact-us-send", class:"btn btn-primary col-md-12"  %>
    <% end %>
  </div>
</div>

app/views/index/device_warning.html.erb
<div class="container">
  <div class="row">
    <div class="col align-self-center">
      <%= image_tag get_aws_url("homblok-tree.png"), id: "device-warning", class:"rounded mx-auto d-block" %>
      <h3 class="text-center mt-5">For the optimal experience please change your device orientation to landscape.</h3>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col d-flex justify-content-center">
      <%= image_tag get_aws_url("white_icons/icons8-ipad-50.png"), class: "device-image rounded mx-auto d-block" %>
      <%= image_tag get_aws_url("white_icons/icons8-sort-right-50.png"), id: "arrow", class: "rounded mx-auto d-block" %>
      <%= image_tag get_aws_url("white_icons/icons8-ipad-mini-50.png"), class: "rounded mx-auto d-block" %>
    </div>
  </div>
</div>
</div>

app/views/index/index.html.erb
<!-- Header Start -->
<%= render 'layouts/header' %>
<!-- Header End -->
<!-- Search Start -->
<%= render 'layouts/search' %>
<!-- Search End -->
<!-- Category Start -->

app/views/index/policy.html.erb
<div class="row">
  <div class="column col-md-2"></div>
  <div class="col-md-8">
    <h2 class="text-center ml-md-4 mt-md-5"><%= image_tag get_aws_url("white_icons/icons8-privacy-50.png"), class: "title-icons ml-md-2 mr-md-1 mb-md-1" %>PRIVACY POLICY</h2>
    <ul class="mt-md-4">
      <p><%= t("business.name") %> recognises the importance of protecting the privacy of information collected about our customers. This privacy policy outlines the type of information that is collected by us on this website, and how we use and protect it.</p>
      <p>We believe that our Privacy Policy complies with the requirements of the Privacy Act 1988. By using our website, you agree with the terms of our current privacy policy as posted in this area of site. If you do not agree with any term in this policy, please do not use the site.</p>
      <h4>Collection of private information</h4>
      <p>As used in this privacy policy, ‘Personal Information’ means personally identifiable information such as your name, street address, email address, telephone number and financial information. We collect this personal information in order to provide our services to you. When you provide us with Personal Information, you are authorising us to use that information in accordance with the terms of this privacy policy.</p>
      <p>We usually collect personal information directly from you although sometimes we may use agents or service providers to do this for us. We do not collect personal information about you if you only browse this website.</p>
      <p>
        When you load photos of your property on our website, you give us explicit permission to use these photos in our marketing & for the use of our carousel on our home page. All photos loaded become the property of <%= t("business.name") %>, & you waive your rights to privacy in relation to these photos.
      </p>
      <h4>Security of information</h4>
      <p>We take reasonable precautions to keep your personal information secure. We understand that you may be concerned about the confidentiality and security of the personal information we collect from you online. Accordingly, we have systems in place to ensure our online dealings with you are as secure and confidential as your dealings with us in person, or on the telephone. We use a variety of security measures including firewalls and secure databases to keep personal information secure from misuse, loss or unauthorised use or disclosure.</p>
      <h4>Changes in our policy</h4>
      <p><%= t("business.name") %> reserves the right to change or remove this privacy policy at our discretion. If we decide to change our privacy policy, we will post those changes here.</p>
      <h4>Who to Contact</h4>
      <p>Please contact <%= t("business.name") %> by our <%= link_to "Contact Us Form", contact_path, class: "link6"%> if you require any further information.</p>
    </ul>
    <div class="mobile-break"></div>
  </div>
  <div class="column col-md-2"></div>
</div>
</div>

app/views/index/step_by_step.html.erb
<div class="row small-screen">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h2 class="text-center ml-md-4 mt-md-5"><%= image_tag get_aws_url("white_icons/icons8-user-manual-50.png"), class: "title-icons ml-md-2 mr-md-1 mb-md-1" %>STEP BY STEP GUIDE</h2>
    <div class="container-fluid g-0">
      <div class="mx-auto list-group my-md-4 list-group-horizontal-sm" id="list-tab" role="tablist">
        <a class="col-md-6 list-group-item list-group-item-action list-home-list active text-center" data-toggle="list" href="#list-home" role="tab" aria-controls="home">BUYING A PROPERTY</a>
        <a class="col-md-6 list-group-item list-group-item-action list-home-list text-center" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">SELLING YOUR PROPERTY</a>
      </div>
    </div>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active mb-md-5" id="list-home" role="tabpanel" aria-labelledby="list-home-list"><%= render "buying_guide" %></div>
      <div class="tab-pane fade mb-md-5" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list"><%= render "selling_guide" %></div>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>