config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'
  get 'tags/show'
  # require 'sidekiq/web'
  # require 'admin_constraint'

  # Sidekiq admin interface
  # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  # Root route
  root 'index#index'

  # Error routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Authentication routes
  post 'signup', to: 'users#create', as: 'signup'
  post 'login', to: 'sessions#create', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'get-started', to: 'index#buy_sell', as: 'get_started'

  # Mobile routes
  get 'mobile', to: 'sessions#mobile', as: 'mobile'
  get 'mobile/signup', to: 'sessions#mobile_signup'
  get 'admin/login', to: 'sessions#mobile_login', as: 'mobile_login'
  get 'welcome-back', to: 'sessions#welcome_back_user', as: 'welcome_back_user'

  # Password routes
  get 'forgot-my-password', to: 'users#forgot_my_password'
  post 'send-token-email', to: 'users#send_token_email'
  get 'new-token-email', to: 'users#new_token_confirmation'
  get 'validate-token/:token', to: 'users#validate_token'
  post 'update-password', to: 'users#update_password'
  post 'change-password', to: 'users#change_password'
  get 'complete_signup/:token', to: 'users#complete_signup'

  # Index page routes
  # get 'background', to: 'index#background'
  # get 'about', to: 'index#about'
  # get 'faq', to: 'index#faq'
  get 'contact', to: 'index#contact'
  post 'contact', to: 'admin#contact_team', as: 'contact_us'
  # get 'step-by-step', to: 'index#step_by_step', as: 'guide'
  get 'privacy-policy', to: 'index#policy', as: 'policy'
  get 'ipad', to: 'index#device_warning'

  # Terms and conditions
  get 'terms-and-conditions', to: 'index#terms_and_conditions'
  get 'accept/:user_id', to: 'users#accept', as: 'accept'

  # Resourceful routes
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :apartments, path: 'listings' do
    resources :comments, only: [:create]
    resources :photo_descriptions, only: [] do
      collection do
        patch :update_all
      end
    end
    resources :market_scores, only: [:create]
    resources :floorplans, only: %i[create destroy update]
  end

  resources :favourites
  resources :photos
  resources :replies
  # config/routes.rb
  resources :tags, path: 'categories', param: :slug do
    resources :child_tags, only: [:show], param: :slug, controller: 'tags'
  end


  # Apartment search routes
  get 'sub-search', to: 'apartments#search_page_two', constraints: lambda { |request| request.query_parameters[:commit] == 'SEARCH' }, as: 'search_page_two'
  get 'search-page', to: 'apartments#search_page_one', as: 'search_page_one'
  get 'search_location/:data', to: 'apartments#search_location'
  get 'submit', to: 'apartments#submit', as: 'submit'
  get 'location-data', to: 'postcodes#typeahead_data'
  get 'property-search', to: 'apartments#new_index'
  get 'location', to: 'apartments#new'
  get 'myproperties', to: 'apartments#owner'
  get 'saved_search/:id', to: 'apartments#index', as: 'saved_search'
  get 'search', to: 'apartments#search'
  get 'searches', to: 'apartments#return_to_search_results', as: 'return_to_search_results'
  get 'photos/featured', to: 'photos#featured'

  # Comments, replies & likes
  post 'comments/:id/:user_id', to: 'apartments#comment'
  delete 'comments/:id', to: 'comments#delete', as: 'delete_comment'
  post 'like/:like_id', to: 'comments#like', as: 'like_comment'

  # Admin section
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/directory', to: 'admin#directory', as: 'admin_directory'
  post 'approve/:id', to: 'admin#approve', as: 'approval'
  post 'revoke/:id', to: 'admin#revoke', as: 'revoke'
  get 'delete/:id', to: 'admin#delete', as: :admin_deletion
  get 'admin/archive/:id', to: 'admin#archive', as: 'admin_archive'
  get 'admin/unarchive/:id', to: 'admin#unarchive', as: 'admin_unarchive'
  get 'admin/archival', to: 'admin#archival', as: 'archival'
  get 'admin/owner/:user_id', to: 'admin#owner', as: 'admin_owner'
  delete 'delete_saved_search/:id', to: 'searches#delete', as: 'delete_saved_search'
  namespace :admin do
    resources :tags do
      collection do
        post 'assign_tags'
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
  # Catch-all route for 404 errors
  # match '*path', to: 'errors#not_found', via: :all
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                            :bigint           not null, primary key
#  accepted_terms_and_conditions :boolean          default(FALSE)
#  email                         :string
#  firstname                     :string
#  is_admin                      :boolean          default(FALSE)
#  last_search_query_match       :datetime
#  password_digest               :string
#  password_token_valid_until    :datetime
#  phone                         :string
#  reset_password_token          :string
#  surname                       :string
#  username                      :string
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#
# Indexes
#
#  index_users_on_email     (email) UNIQUE
#  index_users_on_username  (username) UNIQUE
#

class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar, dependent: :destroy
  has_many :apartments, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :searches, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_milestones, dependent: :destroy

  has_and_belongs_to_many :favourites, class_name: "Apartment"
  accepts_nested_attributes_for :user_milestones

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, on: [:create]

  after_create_commit :send_email_address_confirmation

  def is_admin?
    is_admin == true
  end

  def set_password_token(valid_for:)
    return false unless valid_for.class == ActiveSupport::Duration
    self.update(reset_password_token: SecureRandom.alphanumeric(20))
    self.update(password_token_valid_until: Time.now + valid_for)
  end

  def total_properties
    apartments.load.size
  end

  def accepted_terms?
    accepted_terms_and_conditions == true
  end

  def unlike(comment)
    comment.likes.find_by_user_id(self.id)&.delete
  end

  def like(comment)
    comment.likes.create!(user_id: self.id)
  end

  def milestones
    user_milestones
  end

  def already_liked_comment?(comment)
    comment.likes.find_by_user_id(self.id).present?
  end

  def self.summary
    ap pluck :email,:id,:username
  end

  private

  def send_email_address_confirmation
    User::RequestEmailAddressConfirmationJob.perform(user_id: self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_is_authorised?, except: [:create,:forgot_my_password,:send_token_email, :complete_signup, :new_token_confirmation,:validate_token,:accept], raise: false
  before_action :load_icons, only: [:show]

  def index
    @users = User.all
  end

  def show
    @apartments = current_user.apartments.includes([:amenity,:feature,:descriptor]).order(created_at: :desc).with_attached_photos
    @favourites = current_user.favourites.order(created_at: :desc).with_attached_photos
    @searches = current_user.searches.where.not("title LIKE ?","result%").order('created_at DESC')
    @locations = @searches.map { |search| search.selections.pluck :name }.flatten
  rescue ArgumentError => e
    Rails.logger.error { "error: #{e}" }
    flash[:alert] = "There was an error, please try again."
    render "index"
  end

  def create
    # FIXME refactor this with scenarios eg user, username already present etc
    begin
      @user = User.find_by(email: user_params[:email])
      if @user.present?
        flash[:user_params] = user_params
        redirect_to welcome_back_user_path and return
      else
        @user = User.create!(user_params)
        @user.avatar.attach(user_params[:avatar])
        session[:user_id] = @user.id
        @user.searches.create!(session[:saved_search]) if session[:saved_search].present?
        session.delete "saved_search"
        redirect_to accept_path(@user) and return
      end
      # FIXME userscontrollerhelper not recognised
    rescue ActiveRecord::RecordNotUnique => e
      @message = "That username has been taken, please choose another username " if e.inspect.include? "(username)"
      flash[:updated_user_params] = user_params.permit(:email, :firstname, :surname, :phone)
      redirect_to mobile_signup_path(updated_params) and return
    rescue ActiveRecord::RecordInvalid => e
      errors = e.inspect.split(',')
      @message = errors.each_with_object([]) do |error, message|
        if error.include? "Password confirmation doesn't match Password"
          message << "Password confirmation doesn't match Password. Please try again."
        elsif error.include? "Username has already been taken"
          message << "Please try a different #{(error.include? 'Password') ? 'Password' : 'Username'}. Please ensure it is at least 6 characters long."
        else
          message << "Please try a different #{(error.include? 'Password') ? 'Password' : 'Username'}. Please ensure it is at least 6 characters long."
        end
        flash[:updated_user_params] = user_params.permit(:email, :firstname, :surname, :phone, :username)
        Rails.logger.error {e.inspect}
        flash[:alert] = @message.join(' ')
        redirect_to mobile_signup_path and return
      end
    end
  end

  def accept
    @user = User.find(session[:user_id])
    @user.update!(accepted_terms_and_conditions:true)
    flash[:notice] = "You have registered as #{@user&.username}"
    UserMailer.with(user: @user).welcome_email.deliver_later
    notify_admin_team 'new_user_alert',
      location_info: Geocoder.search(request.remote_ip).first.data,
      email: @user.email,
      firstname: @user.firstname,
      surname: @user.surname,
      username: @user.username,
      phone: @user.phone
    redirect_to previous_page and return @user
  end

  def decline
    redirect_to logout_path
  end

  def update
    current_user.update(update_user_params)
    flash[:notice] = "Your details have been successfully updated."
  rescue StandardError => e
    Rails.logger.error { e.inspect }
    flash[:notice] = "There was a problem updating your details. Please try again later."
  ensure
    redirect_to user_path(current_user)
  end

  def forgot_my_password
  end

  def send_token_email
    @email = password_params[:email]
    @user = User.find_by_email(@email)
    if @user.present?
      @user.set_password_token(valid_for: 15.minutes)
      UserMailer.with(user_id: @user.id, request_url: request.original_url).reset_password_email.deliver_later
      message = "success"
    else
      message = "failure"
    end
    redirect_to new_token_email_path(email: @email, message: message)
  end

  def new_token_confirmation
    @email = params[:email]
    messages = {"failure":"We couldn't find any user with the email","success":"We've sent you a link to reset your password to "}
    @message = messages[params[:message].to_sym]
  end

  def validate_token
    begin
      # receives link and token and validates entry, if valid redirects to new password method
      @user = User.find_by_reset_password_token(params[:token])
      @user.present? && @user.password_token_valid_until < Time.now
      @token = params[:token]
      session[:user_id] = @user.id
      render "update_password"
    rescue Exception => e
      @message = "email address is invalid or token has expired"
      redirect_to forgot_my_password_path
    end
  end

  def update_password
    # updates password in db
    if current_user.update update_password_params
      current_user.update!(reset_password_token:nil)
      redirect_to myproperties_path, alert:  "Password successfully updated" and return
    else
      flash[:alert] = "New password & confirmation fields do not match"
    end
  end

  def change_password
    if current_user.authenticate old_password_params[:old_password]
      current_user.update new_password_params
      flash[:notice] = "Password successfully updated."
    else
      flash[:alert] = "Old password is incorrect or new password & confirmation fields do not match"
    end
    redirect_to user_path(current_user)
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete_signup
    begin
      # receives link and token and validates entry, if valid redirects to new password method
      @user = User.find_by_reset_password_token(params[:token])
      @user.present? && @user.password_token_valid_until < Time.now
      @user.milestones.update(email_address_confirmed: true)
      @token = params[:token]
      session[:user_id] = @user.id
      flash[:alert] = "Congratulations. You have successfully completed your registration."
      redirect_to user_path(@user) and return
    rescue Exception => e
      Rails.logger.error { "error: #{e}" }
      @message = "email address is invalid or token has expired"
      redirect_to forgot_my_password_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.permit(:avatar, :email, :firstname, :surname, :phone, :username, :password, :password_confirmation)
  end

  def terms_params
    params.permit(:user_id)
  end

  def password_params
    params.permit(:email)
  end

  def update_user_params
    params.permit(:email, :firstname, :surname, :phone, :username, :avatar)
  end

  def update_password_params
    params.require(:user).permit(:password,:password_confirmation)
  end

  def old_password_params
    params.require(:user).permit(:old_password)
  end
  def new_password_params
    params.require(:user).permit(:password,:password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_avatar(user)
    if user.avatar.attached?
      image_tag("https://h1.imgix.net/#{user.avatar.key}?usm=20&facepad=1.5&faceindex=1&fit=facearea&mask=ellipse&h=45&w=45&auto=enhance", class: "avatar m-1")
    else
      image_tag(get_aws_url("white_icons/icons8-information-50.png"), class: "iconz mx-1")
    end
  end

  def user_avatar_profile_label
    current_user.avatar.attached? ? "Change Your Profile Picture" : "Add a Profile Picture"
  end

  def profile_pic_url(user)
    "https://h1.imgix.net/#{user.avatar.key}?usm=20&h=250&w=250&auto=enhance"
  end

end

app/views/users/_dropdown.html.erb
<div class="dropstart">
  <a class="btn btn-primary dropdown-toggle" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.username %>
  </a>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <li>
      <%= link_to new_apartment_path, class: 'dropdown-item' do %>
        <div class="d-flex" style="color:white;width: 10rem;">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:1.25rem;margin-right: .5rem;">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v12m-3-2.818.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
          </svg>
          List a Property
        </div>
      <% end %>
    </li>
    <li>
      <a class="dropdown-item" href="<%= user_path(id: current_user.id) %>">
        <div class="d-flex" style="color:white;width: 10rem;">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:1.25rem;margin-right: .5rem;">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
          </svg>
          My Personal Page
        </div>
      </a>
    </li>
    <% if current_user.is_admin? %>
      <li>
        <a class="dropdown-item" href="<%= admin_directory_path %>">
          <div class="d-flex" style="color:white;width: 10rem;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:1.25rem;margin-right: .5rem;">
              <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6V5.25A2.25 2.25 0 0 1 12.75 3h3A2.25 2.25 0 0 1 18 5.25v.75m-7.5 0h7.5m-7.5 0a2.25 2.25 0 0 0-2.25 2.25v9a2.25 2.25 0 0 0 2.25 2.25h7.5a2.25 2.25 0 0 0 2.25-2.25v-9A2.25 2.25 0 0 0 17.25 6h-7.5z" />
            </svg>
            Directory
          </div>
        </a>
      </li>
      <li>
        <a class="dropdown-item" href="<%= admin_path %>">
          <div class="d-flex" style="color:white;width: 10rem;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:1.25rem;margin-right: .5rem;">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 6h6v6H9zM9 12v6H6v-6h3zm6 0v6h3v-6h-3zM6 9h3V6H6v3zm9-3v3h3V6h-3z" />
            </svg>
            Admin
          </div>
        </a>
      </li>
    <% end %>
    <li>
      <a class="dropdown-item" href=<%= logout_path %>>
        <div class="d-flex" style="color:white;width: 10rem;">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:1.25rem;margin-right: .5rem;">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15m-3 0-3-3m0 0 3-3m-3 3H15" />
          </svg>
          Logout
        </div>
      </a>
    </li>
  </ul>
</div>

app/views/users/_favourites.html.erb
<% unless device_is_mobile? || @favourites&.size <= 1 %>
<div id="navArrow"></div>
<% end %>

<div class="row">
<h1 class="my-5 text-center"><%= @favourites.size %></h1>
  <div class="mx-auto col-sm-11 order-sm-2 my-md-5">
    <% if @favourites.present? %>
    <%= render partial: "apartments/show_apartment", locals: { apartments: @favourites} %>
    <% else %>
    <div class="mobile-break"></div>
    <p class="text-center show-property">You haven't saved any properties as favourites yet.</p>
    <br>
    <% end %>
    <div class="mobile-break"></div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.size, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_owner.html.erb
<% unless device_is_mobile? || @apartments&.size < 2 %>
<div id="navArrow"></div>
<% end %>

<div class="row">
  <div class="mx-auto col-md-12 order-sm-2 my-md-5">
    <% if @apartments.present? %>
    <%= render partial: "apartments/show_apartment", locals: { apartments: @apartments} %>
    <% else %>
    <p class="text-center show-property">You haven't added any properties to sell yet.</p>
    <br>
    <% end %>
    <div class="mobile-break"></div>
  </div>
</div>

app/views/users/_password.html.erb
<div class="row mt-md-5">
  <div class="col-md-3" id="contact-column"></div>
  <div class="col-md-6">
    <%= form_for :user, url: change_password_path, local:true, class:"form-group" do |f| %>
      <div class="form-row">
        <div class="col-md-12">
          <%= f.label :password, "Old Password", style: "font-size:small;" %>
          <%= f.password_field :old_password, placeholder: "Your current password", class: "form-control mb-md-3" %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-6">
          <%= f.label :password, "New Password", style: "font-size:small;" %>
          <%= f.password_field :password, placeholder: "Your new password", class: "form-control mb-md-3" %>
        </div>
        <div class="col-md-6">
          <%= f.label :password_confirmation, "Confirm Password", style: "font-size:small;" %>
          <%= f.password_field :password_confirmation, placeholder: "Your new password", class: "form-control mb-md-3" %>
        </div>
      </div>
      <%= f.submit "Create New Password", id: "contact-us-send", class:"btn btn-outline-primary col-md-12"  %>
      <div class="actions">
      <% end %>
    </div>
    <div class="mobile-break"></div>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/users/_saved_searches.html.erb
<% if @searches.blank? %>
  <div class="row">
    <div class="mx-auto col-sm-11 order-sm-2 my-md-5">
      <div class="mobile-break"></div>
      <p class="text-center show-property">You haven't saved any searches yet.</p>
      <br>
    </div>
  <% else %>
    <div class="container">
      <table class="col-md-10 ml-md-5 table table-hover">
        <thead>
          <tr class="d-flex mt-md-2">
            <th class="col-md-2" scope="col"></th>
            <th class="col-md-4" scope="col"></th>
            <th class="col-md-1" scope="col">
              <%= image_tag get_aws_url("white_icons/icons8-bed-100.png"),
           title:"Bedrooms",
           class:"tt iconz m-2",
           data:{toggle:"tooltip", placement:"top"} %>
            </th>
            <th class="col-md-1"
          scope="col">
              <%= image_tag get_aws_url("white_icons/icons8-bathtub-100.png"),
         title:"Bathrooms",
          class:"tt iconz m-2",
          data:{toggle:"tooltip", placement:"top"} %>
            </th>
            <th class="col-md-1" scope="col">
              <%= image_tag get_aws_url("white_icons/icons8-car-50.png"), title: "Parking Spaces",
         class:"tt iconz m-2",
        data:{toggle:"tooltip", placement:"top"} %>
            </th>
            <th class="col-md-1" scope="col">
              <%= image_tag get_aws_url("white_icons/icons8-us-dollar-50.png"),
           title:"Price Range",
            class:"tt iconz m-2",
            data:{toggle:"tooltip", placement:"top"} %>
            </th>
            <th class="col-md-1" scope="col"></th>
            <th class="col-md-1" scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @searches.order('created_at DESC').each do |search| %>
            <% query = eval(search.query) %>
            <tr class="d-flex">
              <th scope="row" 
          class="tt col-md-2"
          data-toggle="tooltip"
          placement="top"
          title="<%= search.title.length > 20 ? search.title.upcase : nil %>"><%= search.title.upcase.first(20) %><%= "..." if search.title.length > 20 %>
              </th>
              <td class="col-md-4">
                <% locations = search.selected_location_names.split(',') %>
                <% locations.each do |location| %>
                  <span> <%= location %></span><br>
                <% end %>
              </td>
              <td class="col-md-1">
                <%= query["min_bedrooms"] %> - <%= query["max_bedrooms"] %>
              </td>
              <td class="col-md-1">
                <%= query["min_bathrooms"] %> - <%= query["max_bathrooms"] %>
              </td>
              <td class="col-md-1">
                <%= query["min_parking"] %> - <%= query["max_parking"] %>
              </td>
              <td class="col-md-1">
                $<%= number_to_human(query["min_pricing"], precision: 2) %> - $<%= number_to_human(query["max_pricing"], precision: 2) %>
              </td>
              <td class="col-md-1">
                <%= link_to("Search", saved_search_path(id: search.id, "run-saved-search":true),
         title:"Click to search",
          class: "tt run-saved-search ml-2",
          data:{toggle:"tooltip", placement:"top"} ) %>
              </td>
              <td class="col-md-1">
                <%= link_to("Delete", delete_saved_search_path(search.id),
         title:"Click to delete", method: "delete", id:"delete-search",
          class: "tt ml-2" ,
          data:{toggle:"tooltip", placement:"top"}) %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/forgot_my_password.html.erb
<div class="row">
  <div class="column col-md-4" id="contact-column"></div>
  <div class="col-md-4 mt-md-5">
    <h1 class="text-center mt-md-5 mb-md-3">FORGOT PASSWORD?</h1>
    <p class="text-center">We will send you a new one.</p>
    <%= form_with url: send_token_email_path, local:true, class:"form-group" do |f| %>
      <%= f.text_field :email, placeholder: "Your email address", class: "form-control mb-md-3" %>
      <%= f.submit "Reset My Password", id: "contact-us-send", class:"btn btn-outline-primary col-md-12"  %>
    <% end %>
  </div>
  <div class="column col-md-4"></div>
</div>
<div class="col-md-5 white mt-md-5"></div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/update_password.html.erb
<div class="row" style="margin: -1rem 0 !important;">
  <div class="column col-md-4 my-md-5" id="contact-column"></div>
  <div class="col-md-4 my-md-5">
    <h1 class="text-center mt-md-5 my-md-5">Update your password</h1>
    <%= form_for :user, url: update_password_path, class: "form-group alert alert-info", method: "post" do |f| %>
    <%= f.hidden_field :reset_password_token, value: @token, class: "form-control mb-md-1" %>
    <%= f.label "New Password" %>
    <%= f.text_field :password, class: "form-control mb-md-1" %>
    <%= f.label "Repeat New Password" %>
    <%= f.text_field :password_confirmation, class: "form-control mb-md-1" %>
    <%= f.submit "Update", class: "btn btn-outline-primary col-md-12 my-md-5" %>
    <% end %>
  </div>
  <div class="column col-md-4 my-md-5"></div>
</div>