config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'
  get 'tags/show'
  # require 'sidekiq/web'
  # require 'admin_constraint'

  # Sidekiq admin interface
  # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  # Root route
  root 'index#index'

  # Error routes
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Authentication routes
  post 'signup', to: 'users#create', as: 'signup'
  post 'login', to: 'sessions#create', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'get-started', to: 'index#buy_sell', as: 'get_started'

  # Mobile routes
  get 'mobile', to: 'sessions#mobile', as: 'mobile'
  get 'mobile/signup', to: 'sessions#mobile_signup'
  get 'admin/login', to: 'sessions#mobile_login', as: 'mobile_login'
  get 'welcome-back', to: 'sessions#welcome_back_user', as: 'welcome_back_user'

  # Password routes
  get 'forgot-my-password', to: 'users#forgot_my_password'
  post 'send-token-email', to: 'users#send_token_email'
  get 'new-token-email', to: 'users#new_token_confirmation'
  get 'validate-token/:token', to: 'users#validate_token'
  post 'update-password', to: 'users#update_password'
  post 'change-password', to: 'users#change_password'
  get 'complete_signup/:token', to: 'users#complete_signup'

  # Index page routes
  # get 'background', to: 'index#background'
  # get 'about', to: 'index#about'
  # get 'faq', to: 'index#faq'
  get 'contact', to: 'index#contact'
  post 'contact', to: 'admin#contact_team', as: 'contact_us'
  # get 'step-by-step', to: 'index#step_by_step', as: 'guide'
  get 'privacy-policy', to: 'index#policy', as: 'policy'
  get 'ipad', to: 'index#device_warning'

  # Terms and conditions
  get 'terms-and-conditions', to: 'index#terms_and_conditions'
  get 'accept/:user_id', to: 'users#accept', as: 'accept'

  # Resourceful routes
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :apartments, path: 'listings' do
    resources :comments, only: [:create]
    resources :photo_descriptions, only: [] do
      collection do
        patch :update_all
      end
    end
    resources :market_scores, only: [:create]
    resources :floorplans, only: %i[create destroy update]
  end

  resources :favourites
  resources :photos
  resources :replies
  # config/routes.rb
  resources :tags, path: 'categories', param: :slug do
    resources :child_tags, only: [:show], param: :slug, controller: 'tags'
  end


  # Apartment search routes
  get 'sub-search', to: 'apartments#search_page_two', constraints: lambda { |request| request.query_parameters[:commit] == 'SEARCH' }, as: 'search_page_two'
  get 'search-page', to: 'apartments#search_page_one', as: 'search_page_one'
  get 'search_location/:data', to: 'apartments#search_location'
  get 'submit', to: 'apartments#submit', as: 'submit'
  get 'location-data', to: 'postcodes#typeahead_data'
  get 'property-search', to: 'apartments#new_index'
  get 'location', to: 'apartments#new'
  get 'myproperties', to: 'apartments#owner'
  get 'saved_search/:id', to: 'apartments#index', as: 'saved_search'
  get 'search', to: 'apartments#search'
  get 'searches', to: 'apartments#return_to_search_results', as: 'return_to_search_results'
  get 'photos/featured', to: 'photos#featured'

  # Comments, replies & likes
  post 'comments/:id/:user_id', to: 'apartments#comment'
  delete 'comments/:id', to: 'comments#delete', as: 'delete_comment'
  post 'like/:like_id', to: 'comments#like', as: 'like_comment'

  # Admin section
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/directory', to: 'admin#directory', as: 'admin_directory'
  post 'approve/:id', to: 'admin#approve', as: 'approval'
  post 'revoke/:id', to: 'admin#revoke', as: 'revoke'
  get 'delete/:id', to: 'admin#delete', as: :admin_deletion
  get 'admin/archive/:id', to: 'admin#archive', as: 'admin_archive'
  get 'admin/unarchive/:id', to: 'admin#unarchive', as: 'admin_unarchive'
  get 'admin/archival', to: 'admin#archival', as: 'archival'
  get 'admin/owner/:user_id', to: 'admin#owner', as: 'admin_owner'
  delete 'delete_saved_search/:id', to: 'searches#delete', as: 'delete_saved_search'
  namespace :admin do
    resources :tags do
      collection do
        post 'assign_tags'
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
  # Catch-all route for 404 errors
  # match '*path', to: 'errors#not_found', via: :all
end

app/models/apartment.rb
# == Schema Information
#
# Table name: apartments
#
#  id                :bigint           not null, primary key
#  approved          :boolean          default(FALSE)
#  archived          :boolean          default(FALSE)
#  asking_price      :integer
#  bathrooms         :integer
#  bedrooms          :integer
#  description       :text
#  display_option    :string           default("both")
#  house_number      :text
#  internal_space    :integer
#  land_size         :integer
#  latitude          :float
#  longitude         :float
#  name              :string
#  parking_spaces    :integer
#  postcode          :integer
#  slug              :string
#  state             :text
#  strata            :boolean          default(FALSE)
#  street_address    :text
#  suburb            :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  featured_photo_id :bigint
#  location_id       :bigint
#  property_type_id  :bigint
#  user_id           :bigint
#
# Indexes
#
#  index_apartments_on_latitude_and_longitude  (latitude,longitude)
#  index_apartments_on_location_id             (location_id)
#  index_apartments_on_property_type_id        (property_type_id)
#  index_apartments_on_slug                    (slug) UNIQUE
#  index_apartments_on_user_id                 (user_id)
#
class Apartment < ApplicationRecord

  extend FriendlyId
  friendly_id :slug_address, use: :slugged

  before_destroy :purge_from_storage
  after_create :create_associations

  # TODO change this to get lat long from db
  after_save :run_geocode_job
  geocoded_by :suburb

  belongs_to :user
  belongs_to :property_type

  belongs_to :location, optional: true
  has_and_belongs_to_many :searches
  has_and_belongs_to_many :fans, class_name: "User"

  has_one :descriptor, dependent: :destroy
  has_one :feature, dependent: :destroy
  has_one :amenity, dependent: :destroy

  has_many_attached :photos, dependent: :destroy
  has_many_attached :floorplans, dependent: :destroy

  has_many :apartment_tags, dependent: :destroy
  has_many :tags, through: :apartment_tags
  has_many :comments, dependent: :destroy
  has_many :market_ratings, dependent: :destroy
  has_many :photo_descriptions, dependent: :destroy
  has_many :property_milestones, dependent: :destroy
  accepts_nested_attributes_for :feature, :descriptor, :amenity, :comments, :photo_descriptions, :property_milestones

  scope :not_owned_by, ->(user) { where.not(user_id: user.id) }

  validates :display_option, inclusion: { in: %w(name address both) }

  def display_text
    case display_option
    when 'name'
      name
    when 'address'
      slug_address
    else
      "#{name} | #{slug_address}"
    end
  end

  def create_associations
    Feature.create! apartment: self
    Descriptor.create! apartment: self
    Amenity.create! apartment: self
  end

  def owner
    user
  end

  def owner_is(user_model)
    user == user_model
  end

  def image_url
    super || default_image
  end

  def slug_address
    "#{street_address} #{suburb}"
  end

  def address_line_1
    "#{street_address}".titlecase
  end

  def address_line_2
    "#{suburb} #{postcode}".titlecase
  end

  def full_address
    "#{house_number} #{street_address&.titlecase} #{suburb&.titlecase} #{postcode}"
  end

  def full_address_line_1
    "#{house_number} #{street_address}".titlecase
  end

  def approve
    self.update!("approved": true)
  end

  def revoke_approval
    self.update!("approved": false)
  end

  def self.approved?
    find_by(:approved => true)
  end

  def self.archived
    where(:archived => true)
  end

  def self.un_archived
    where(:archived => false)
  end

  def archive
    self.update!("archived":true)
  end

  def unarchive
    self.update!("archived":false)
  end

  def milestones
    property_milestones
  end

  def update_postcode
    begin
      result = Geocoder.search([self.latitude,self.longitude])
      self.update!(postcode: result.first.postal_code)
    rescue Exception => e
      Rails.logger.debug { "#{e}" }
      return nil
    end
  end

  def self.find_matching_properties(asking_prices,params)
    where("asking_price BETWEEN :min_pricing AND :max_pricing", {min_pricing:asking_prices[:min_asking_price], max_pricing:asking_prices[:max_asking_price]})
    .where("bedrooms BETWEEN :min_bedrooms AND :max_bedrooms", {min_bedrooms: params["min_bedrooms"].to_i, max_bedrooms: params["max_bedrooms"].to_i})
    .where("bathrooms BETWEEN :min_bathrooms AND :max_bathrooms", {min_bathrooms: params["min_bathrooms"].to_i, max_bathrooms: params["max_bathrooms"].to_i } )
    .where("parking_spaces BETWEEN :min_parking_spaces AND :max_parking_spaces", {min_parking_spaces: params["min_parking"].to_i, max_parking_spaces: params["max_parking"].to_i})
    .where("approved":true)
    .where("archived":false)
  end

  def average_suggested_price
    market_ratings.average(:suggested_price).round if market_ratings.present?
  end

  def median_suggested_price
    array = market_ratings.pluck(:suggested_price)
    sorted = array.sort
    len = sorted.length
    (sorted[(len - 1) / 2] + sorted[len / 2]) / 2.0
  end

  def delete_photo_and_description(photo_id)
    photo_description = self.photo_descriptions.find_by_blob_id(photo_id)
    photo_description&.destroy!
    photo = self.photos.find_by(id: photo_id)
    photo&.purge
  end

  def presort_photos
    photos = []
    featured_photo = photo_descriptions.find_by(featured: true)&.blob_id

    begin
      # Retrieve the ordered list of photo IDs
      photo_list = self.photos.order(created_at: :desc).pluck(:id)

      # Remove the featured photo ID and place it at the start if it exists
      if featured_photo
        photo_list.delete(featured_photo)
        photo_list.unshift(featured_photo)
      end

      # Build the CASE statement for ordering based on the photo list
      order_clause = photo_list.each_with_index.map { |id, index| "WHEN id = #{id} THEN #{index}" }.join(' ')

      # Fetch the photos ordered by the specified array order
      photos = self.photos.where(id: photo_list).order(Arel.sql("CASE #{order_clause} END"))
    rescue StandardError => e
      logger.error "Error in presorting photos: #{e.message}"
      return self.photos
    end

    photos
  end


  def set_featured_photo(id)
    photo_descriptions.find_by(featured:true) && photo_descriptions.find_by(featured:true).update(featured:false)
    update! featured_photo_id:id
    pd = photo_descriptions.find_or_initialize_by(blob_id:id)
    pd.update! featured:true
  end

  def purge_from_storage
    photos.each do |pic|
      pic.purge_later
      logger.info { "Photo with ID: #{pic.id} PURGED!" }
    end
  end

  def congratulate_owner_on_first_drafted_property
    return false if self.property_milestone.minimum_completed == true
    self.property_milestone.update! minimum_completed: true
    # FIXME property_milestone.congratulated_on_first_property.freeze
  end

  def self.crow_flies(collection_of_two_points)
    two_points = collection_of_two_points
    raise StandardError.new "2 apartments are not present" if two_points.length != 2
    locations = two_points.map {|a| "#{a.latitude},#{a.longitude}" }
    Geocoder::Calculations.distance_between(locations[0],locations[1])
  end

  def run_geocode_job
    GeocodeApartmentJob.perform(self.id)
  end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
  include PostcodesHelper

  def save_search_query(title:,postcode_list:)
    @search_title = title
    SaveSearchResultsJob.perform(
      user: ( current_user if current_user.present? ),
      apartments_collection:nil,
      search_query: @params.to_unsafe_hash,
      search_title: @search_title,
    postcode_list: postcode_list )
  end

  def assign_title(saved_search_title)
    search_title = saved_search_title.present? ? saved_search_title : "result#{SecureRandom.hex(2)}"
  end

  # FIXME needed?
  # def prepare_search_criteria_from_params(asking_price_params,search_query)
  #   asking_prices = sort_asking_prices(asking_price_params)
  #   criteria = Apartment.includes([:user,:amenity,:feature,:descriptor]).find_matching_properties(asking_prices,search_query)
  # end

  def create_search_parameters
    parsed_params = search_params.to_unsafe_hash
    parsed_params["postcode"] = Apartment.remove_duplicate_postcodes(search_params[:postcode])
    draft_saved_search = session[:saved_search].present? ? session[:saved_search] : {query:parsed_params,title:saved_search_title_params[:saved_search_title]}
    if current_user.present? && draft_saved_search.present?
      current_user.searches.create!(draft_saved_search)
      session.delete "saved_search" if session[:saved_search].present?
    else
      session[:saved_search] = draft_saved_search
    end
  end

  # FIXME required?
  def default_image
    image_tag("default.png")
  end

  def currency_to_number(currency)
    currency.to_s.gsub(/[$,]/,'').to_f
  end

  def select_tag_helper(apartment)
    @featured = PhotoDescription.find(apartment.featured_photo_id)
    @options_array = apartment.photos.pluck(:id).map.with_index {|id,index| ["PHOTO #{index+1}",id]}
    @actions_array = [["Choose a feature photo","set_featured_photo"],["Delete Photo","delete_photo"]]
  end

  def apartment_carousel_image_url(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=480&w=800&crop=entropy"
  end

  def apartment_results_page_image_url(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=400&w=612&crop=entropy"
  end

  def photo_edit_page_apartment_image_url(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=300&w=300&crop=entropy"
  end

  def ipad_photo_edit_page_apartment_image_url(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=400&w=650&crop=entropy"
  end

  def mobile_photo_edit_page_apartment_image_url(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=370&w=231&crop=entropy"
  end

  def photo_edit_page_apartment_image_ursl(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=250&w=250&crop=entropy"
  end

  def photo_update_page_apartment_image_url(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=300&w=300&crop=entropy"
  end

  def photo_edit_page_mobile_image_url(image)
    "https://propertyser.imgix.net/#{image.key}?usm=20&auto=format%2Cenhance&fit=crop&h=300&w=238&crop=entropy"
  end

  def floorplan_apartment_page_url(floorplan)
    "https://propertyser.imgix.net/#{floorplan.key}?usm=20&auto=format%2Cenhance&fit=crop&h=300&w=400&crop=entropy"
  end
end

app/views/apartments/_apartments_with_admin_options.html.erb
<%= form_with(url: assign_tags_admin_tags_path, method: :post, local: true) do |form| %>
  <div class="row d-flex flex-wrap">
    <!-- Submit button for all apartments -->
    <div class="col-12 align-self-end my-2">
      <%= form.submit "Save Categories", class: "btn btn-primary d-none", id: "category-submit" do %>
        <span class="d-block p-2 text-bg-danger">d-block</span>
      <% end %>
    </div>
    <% @apartments.each do |apartment| %>
      <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
        <div class="card"  style="min-width: 18rem;min-height:380px;">
          <div class="card-body apartment-card">
            <div class="row">
              <!-- Image and link -->

                <% pic = apartment.photos&.first %>
                <% tag = pic.present? ? image_tag(pic, alt: "", class: "img-fluid img-thumbnail property-thumbnail") : "<div class='property-thumbnail small text-decoration-none'>There was a problem loading the image.</div>".html_safe  %>
                <div style="max-height: 180px;overflow: clip;display: flex;justify-content: center;align-items: center;">
                  <%= link_to tag, apartment_path(apartment), class: "alert-link" %>
                </div>

              <!-- Address and property details -->
              <div class="card-body">
                <h5 class="card-title">
                  <%= link_to apartment.full_address_line_1, apartment_path(apartment), class: "alert-link nounderline" %>
                </h5>
                <h5 class="card-title">
                  <%= link_to apartment.address_line_2, apartment_path(apartment), class: "alert-link nounderline" %>
                </h5>
                <div class="card-text">
                  <%= render partial: "apartments/property_values", locals: {apartment: apartment} %>
                </div>
              </div>
              <!-- Favourites widget -->
              <div class="col-md-1 order-md-4 d-flex align-items-center">
                <%= render partial: "favourites/widget", locals: {apartment: apartment} %>
              </div>
            </div>
            <!-- Tag selection -->
            <div class="field w-100">
              <%= form.label "Categories" %>
              <%= form.collection_select "apartments[#{apartment.id}][tag_ids]", @child_tags, :id, :name, { selected: apartment.tag_ids }, { multiple: true, class: "form-control tag-select" } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/apartments/_display_address.html.erb
<!-- app/views/apartments/_display_address.html.erb -->
<% case apartment.display_option %>
<% when 'name' %>
  <h6 class="card-title ml-3 mt-3">
    <%= link_to apartment.display_text.html_safe, apartment_path(apartment, title: search_title), class: "alert-link nounderline" %>
  </h6>
<% when 'address' %>
  <%= render partial: "apartments/display_address_only", locals: { apartment: apartment, search_title: search_title } %>
<% else %> <!-- 'both' option -->
  <h6 class="card-title ml-3 mt-3">
    <%= link_to apartment.display_text, apartment_path(apartment, title: search_title), class: "alert-link nounderline" %>
  </h6>
  <%= render partial: "apartments/display_address_only", locals: { apartment: apartment, search_title: search_title } %>
<% end %>
<% if current_user&.is_admin? %>
  <h6 class="card-subtitle mb-2 text-muted ml-3 mt-2">
    Full address: <%= apartment.full_address %>
  </h6>
<% end %>

app/views/apartments/_display_address_only.html.erb
<!-- app/views/apartments/_display_address_only.html.erb -->
<% if apartment.slug_address.length < 19 %>
  <% if current_user.blank? %>
    <h6 class="card-title ml-3 mt-3 tt disable-select blur" title="Become a member to see the full address." data-toggle="tooltip" data-placement="top">
      <%= apartment.slug_address %>
    </h6>
  <% else %>
    <h6 class="card-title ml-3 mt-3">
      <%= link_to apartment.slug_address, apartment_path(apartment, title: search_title), class: "alert-link nounderline" %>
    </h6>
  <% end %>
<% else %>
  <% if current_user.blank? %>
    <h6 class="card-title ml-3 mt-3 tt disable-select blur" title="Become a member to see the full address." data-toggle="tooltip" data-placement="top">
      <%= apartment.slug_address %>
    </h6>
  <% else %>
    <h6 class="card-title ml-3 mt-3">
      <%= link_to apartment.slug_address, apartment_path(apartment, title: search_title), class: "alert-link nounderline" %>
    </h6>
  <% end %>
<% end %>

app/views/apartments/_land_size_internal_space.html.erb
<div class="mt-md-2">
  <%= apartment.internal_space.present? && apartment.internal_space > 0 ? 
    "<h5>Internal Space</h5><span class='my-3 show-property tt' title='Internal Space' data-toggle-tooltip, data-placement-top> #{apartment.internal_space}\u{33A1}</span>".html_safe : nil %>
  <%= apartment.land_size.present? && apartment.land_size > 0 ?
    
    "<h5>Land Size</h5><span class='my-3 show-property tt' title='Land Size' data-toggle-tooltip, data-placement-top> #{apartment.land_size}\u{33A1}</span>".html_safe : nil %>
</div>

app/views/apartments/_market_ratings.html.erb
<div class="my-md-4 display-inline">
  <h5 class="mt-3 mb-1 property-info"><%= image_tag(get_aws_url("new_system_icons/price-small.svg"), class: "iconz mr-md-1 mt-md-1") %>Asking Price</h5>
  <p class="show-property">$<%= number_with_delimiter @apartment.asking_price %></p>
</div>
<% if current_user.id == @apartment.user_id || current_user.is_admin? %>
  <div class="my-md-4">
    <h5 class="mt-3 mb-1"><%= "Average Voted Price" %></h5>
    <p class="show-property"><%= @apartment.market_ratings.exists? ? "$"+number_with_delimiter(@apartment.average_suggested_price) : "No feedback yet" %></p>
  </div>
<% end %>
<% if @apartment.user_id != current_user.id %>
  <% if @self_rating.blank? %>
    <div>
      <%= form_for @apartment.market_ratings.new, url: apartment_market_scores_path(:apartment_id => @apartment.id, ), class: "form-control" do |f| %>
        <div class="form-row">
          <%= image_tag(get_aws_url("white_icons/icons8-expensive-64.png"), class: "iconz #{device_is_mobile? ? 'my-2' : 'mt-2'}  mr-1") %>
          <%= f.number_field :suggested_price, class: "form-control #{device_is_mobile? ? 'col-9' : 'col-10'} ml-2 mt-2 reply-box", placeholder:"How much would you offer?" %>
          <%= f.button :submit, id: "mobile-feedback-submit", class: "m-2 btn btn-outline-primary" do %>
            <%= image_tag(get_aws_url('white_icons/icons8-checkmark-40.png')).html_safe %>
          <% end if device_is_mobile? %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="my-md-4">
      <h5><%= current_user.is_admin? ? "#{current_user.username}"+" voted" : "YOU VOTED".humanize %></h5>
      <h5>$<%= number_with_delimiter @self_rating.suggested_price %></h5>
    </div>
  <% end %>
<% end %>

app/views/apartments/_property_type.html.erb
<div class="row my-5"></div>
<div class="row my-5"></div>
<div class="row">
  <div class="col-md-12 mt-sm-3">
    <%= f.label :property_type_id, "What Type of Property?" %>
    <%= f.collection_select(:property_type_id, PropertyType.all, :id, :name, { selected: apartment.property_type_id, prompt: "CHOOSE ONE" }, class: "form-select my-md-3") %>
  </div>
</div>

app/views/apartments/_saved_searches.html.slim
- if @searches.present? && device_is_mobile?
    #accordionSavedSearch.accordion
      - @searches.order('created_at DESC').each_with_index do |search,index|
        - query = eval(search.query)
        - selections = search.selected_location_names
        - @toggle = index > 0 ? "collapse show" : "collapse"
        .card
          .card-header id = "heading#{index}"
            h5.mb-0.text-center
              button.btn.btn-link.collapsed [type="button" data-toggle="collapse" data-target="#collapse#{index}" aria-expanded="true" aria-controls="collapse#{index}"]
                = image_tag "dark_icons/icons8-home-address-50.png", class: "tt iconz mb-md-2 mr-md-1"
                = search.title.upcase
          .collapse [id= "collapse#{index}" aria-labelledby="heading#{index}" data-parent="#accordionSavedSearch"]
            .card-body
              .row
              = link_to("Search", saved_search_path(id: search.id, "run-saved-search":true), {title:"Click to search", class: "run-saved-search btn btn-outline-primary col-5 ml-2"})
              = link_to("Delete", delete_saved_search_path(search.id),{title:"Delete", method: "delete", id:"delete-search", class: "btn btn-outline-primary col-5 ml-2"})
              br
              br
              | #{image_tag "dark_icons/icons8-bed-100.png", title:"Bedrooms", class:"tt iconz", data:{toggle:"tooltip", placement:"top"}} #{query["min_bedrooms"]}-#{query["max_bedrooms"]}
              br
              br 
              | #{image_tag "dark_icons/icons8-bathtub-100.png",title: "Bathrooms", class:"tt iconz", data:{toggle:"tooltip", placement:"top"}} #{query["min_bathrooms"]}-#{query["max_bathrooms"]} 
              br
              br
              | #{image_tag "dark_icons/icons8-car-50.png",title: "Parking Spaces", class:"tt iconz" , data:{toggle:"tooltip", placement:"top"}} #{query["min_parking"]}-#{query["max_parking"]}
              br
              br 
              | #{image_tag "dark_icons/icons8-us-dollar-50.png", title:"Price Range", class:"tt iconz mb-md-2 mx-md-1", data:{toggle:"tooltip", placement:"top"}} $#{number_to_human(query["min_pricing"], precision: 2)}-$#{number_to_human(query["max_pricing"], precision: 2)}
              br
              br
              | #{ image_tag "dark_icons/icons8-home-address-50.png", class: "tt iconz" }
              small.text-muted
                = selections.upcase
              br

      .mobile-break
- if @searches.present? && !device_is_mobile?
  .row.mt-md-1
    ul
      = image_tag "dark_icons/icons8-search-50.png", class: "tt iconz mb-md-3", id:"saved-search-icon"
      p.d-inline.property-title.mt-md-2.ml-md-2 SAVED SEARCHES
      - @searches.order('created_at DESC').each do |search|
        - query = eval(search.query)
        - selections = search.selected_location_names
        li
          .row
            small.text-muted.ml-md-2
              = link_to "#{search.title.upcase}".html_safe, saved_search_path(id: search.id, "run-saved-search":true), class: "run-saved-search", title:"Click to search"
          .row
            small.text-muted
              = image_tag "dark_icons/icons8-home-address-50.png", class: "tt iconz mb-md-2 mr-md-1"
              = selections.upcase
              br
              | #{image_tag "dark_icons/icons8-us-dollar-50.png", title:"Price Range", class:"tt iconz mb-md-2 mx-md-1", data:{toggle:"tooltip", placement:"top"}} $#{number_to_human(query["min_pricing"], precision: 2)}-$#{number_to_human(query["max_pricing"], precision: 2)} 
              | #{image_tag "dark_icons/icons8-bed-100.png", title:"Bedrooms", class:"tt iconz mb-md-2 mx-md-1", data:{toggle:"tooltip", placement:"top"}}
              | #{query["min_bedrooms"]}-#{query["max_bedrooms"]} 
              | #{image_tag "dark_icons/icons8-bathtub-100.png",title: "Bathrooms", class:"tt iconz mb-md-2 mx-md-1", data:{toggle:"tooltip", placement:"top"}} #{query["min_bathrooms"]}-#{query["max_bathrooms"]} 
              | #{image_tag "dark_icons/icons8-car-50.png",title: "Parking Spaces", class:"tt iconz mb-md-2 mx-md-1" , data:{toggle:"tooltip", placement:"top"}}
              | #{query["min_parking"]}-#{query["max_parking"]}     
              = link_to("#{image_tag "dark_icons/icons8-trash-64.png",title: "Delete", class:"tt iconz mb-md-2 mx-md-1" , data:{toggle:"tooltip", placement:"top"}}".html_safe, delete_saved_search_path(search.id),{title:"Delete", method: "delete", id:"delete-search"})